#!/bin/sh

. config/options

$SCRIPTS/checkdeps build || exit 1

rm -rf $BUILD/iso
mkdir -p $BUILD/iso
export INSTALL=$BUILD/iso

$SCRIPTS/image "$1"
$SCRIPTS/installdev xorriso

case $TARGET_ARCH in
  i386|x86_64)
    MKISOFS_ARCH="-no-emul-boot \
                  -boot-info-table \
                  -boot-load-size 4 \
                  -b isolinux/isolinux.bin \
                  -c isolinux/boot.catalog \
                  -isohybrid-mbr $ROOT/$TOOLCHAIN/share/syslinux/isohdpfx.bin \
                  -partition_offset 16 \
                  -eltorito-alt-boot \
                  -no-emul-boot"
    ;;
  powerpc|powerpc64)
    MKISOFS_ARCH="-hfs \
                  -part \
                  -no-desktop \
                  -map $CONFIG/maps \
                  -hfs-volid $DISTRONAME_UC \
                  -hfs-bless $BUILD/iso/$DISTRODIR/boot"
    ;;
esac

mkdir -p $BINROOT
$ROOT/$TOOLCHAIN/bin/xorriso \
        -as mkisofs \
        -quiet -no-pad -V $DISTRONAME_UC -volset $DISTRONAME_UC \
        -publisher "The SifBoX team (forum.sifteam.eu)" \
        -p "The SifBoX team (forum.sifteam.eu)" \
        -A "MKISOFS ISO 9660/HFS FILESYSTEM BUILDER" \
        -z -D -r -J $MKISOFS_ARCH \
        $BUILD/iso > $ISO

cat > $ISO.json << "EOF"
{
   "name": "SifBox",
   "version": "VERS_ISO",
   "date": "DATE",
   "description": "Versione stabile",
   "kernel_version": "KERN_VER",
   "vdr_version": "VDR_VERSION",
   "kodi_version": "KODI_VERSION",
   "arch": "ARCH",
   "platform": "PLATFORM"
}
EOF

DATE=`date +%d-%m-%Y`
VERS_ISO=`cat $ROOT/VERSION`
VDR_VERSION=`grep -E '^PKG_VERSION' $ROOT/packages/multimedia/vdr/meta | cut -f1 |cut -f 2 -d=`
KERN_VER=`grep -E '^PKG_VERSION' $ROOT/packages/system/linux/meta | cut -f1 |cut -f 2 -d=`
get_meta kodi
KODI_VERSION=`echo $PKG_VERSION |tr helix Helix |tr frodo Frodo`

sed -i "s|\"DATE\"|\"$DATE\"|" $ISO.json
sed -i "s|\"VERS_ISO\"|\"$VERS_ISO\"|" $ISO.json
sed -i "s|\"KERN_VER\"|\"$KERN_VER\"|" $ISO.json
sed -i "s|\"ARCH\"|\"$TARGET_ARCH\"|" $ISO.json
sed -i "s|\"PLATFORM\"|\"$TARGET_MACHINE\"|" $ISO.json
sed -i "s|\"VDR_VERSION\"|\"$VDR_VERSION\"|" $ISO.json
sed -i "s|\"KODI_VERSION\"|\"$KODI_VERSION\"|" $ISO.json
exit 0
