#!/bin/sh

. config/options

$SCRIPTS/checkdeps build || exit 1

if [ "$TTC_XZ" = yes ] ; then
  TARBALL_NAME=$XZ_NAME
else
  TARBALL_NAME=$TBZ2_NAME
fi

rm -rf $TARBALL_NAME $TARBALL_DIR
mkdir -p $TARBALL_DIR

[ "$NOROOTFS" = 1 ] || $SCRIPTS/rootfs

cp -PR $ROOTFS/* $TARBALL_DIR

. $CONFIG_MACHINE/meta

if [ -n "$MACHINE_XLOADER_CONFIG" ]; then
  $SCRIPTS/installdev x-loader
  mkdir -p $TARBALL_DIR/boot
  cp -P $ROOT/$TOOLCHAIN/share/x-loader/* $TARBALL_DIR/boot
fi

if [ -n "$MACHINE_UBOOT_CONFIG" ]; then
  $SCRIPTS/installdev u-boot
  mkdir -p $TARBALL_DIR/boot
  cp -PR $ROOT/$TOOLCHAIN/share/u-boot/* $TARBALL_DIR/boot
fi

if [ "$TARGET_MACHINE" = utilite ] ; then
  cp -P $SCRIPTS/install-utilite $TARBALL_DIR/bin/install-utilite
fi

tar cpaf $TARBALL_NAME -C $TARBALL_DIR .

cat > $TARBALL_NAME.json << "EOF"
{
   "name": "SifBox",
   "version": "VERS_ISO",
   "date": "DATE",
   "description": "Versione stabile",
   "kernel_version": "KERN_VER",
   "vdr_version": "VDR_VERSION",
   "kodi_version": "KODI_VERSION",
   "arch": "ARCH",
   "platform": "PLATFORM"
}
EOF

DATE=`date +%d-%m-%Y`
VERS_ISO=`cat $ROOT/VERSION`
VDR_VERSION=`grep -E '^PKG_VERSION' $ROOT/packages/multimedia/vdr/meta | cut -f1 |cut -f 2 -d=`
KERN_VER=`grep -E '^PKG_VERSION' $ROOT/packages/system/linux/meta | cut -f1 |cut -f 2 -d=`
get_meta kodi
KODI_VERSION=`echo $PKG_VERSION |tr helix Helix |tr frodo Frodo`

sed -i "s|\"DATE\"|\"$DATE\"|" $TARBALL_NAME.json
sed -i "s|\"VERS_ISO\"|\"$VERS_ISO\"|" $TARBALL_NAME.json
sed -i "s|\"KERN_VER\"|\"$KERN_VER\"|" $TARBALL_NAME.json
sed -i "s|\"ARCH\"|\"$TARGET_ARCH\"|" $TARBALL_NAME.json
sed -i "s|\"PLATFORM\"|\"$TARGET_MACHINE\"|" $TARBALL_NAME.json
sed -i "s|\"VDR_VERSION\"|\"$VDR_VERSION\"|" $TARBALL_NAME.json
sed -i "s|\"KODI_VERSION\"|\"$KODI_VERSION\"|" $TARBALL_NAME.json

if [ "$TARGET_MACHINE" = "tbs2910" ]; then
   #mkdir -p $BINROOT/install_dir
   cp -r $CONFIG_MACHINE/TBS-MatrixTV $BINROOT
   cp $ROOT/$TOOLCHAIN/share/u-boot/u-boot.bin "$BINROOT/TBS-MatrixTV/Profiles/MX6Q Linux Update/OS Firmware/files/u-boot-mx6q-sabresd.bin"
   cp $TARBALL_DIR/boot/uImage "$BINROOT/TBS-MatrixTV/Profiles/MX6Q Linux Update/OS Firmware/files/"
   mv $XZ_NAME "$BINROOT/TBS-MatrixTV/Profiles/MX6Q Linux Update/OS Firmware/files/"
   XZ_NAME=$TARBALL_NAME.xz
   tar cpaf $XZ_NAME -C $BINROOT/TBS-MatrixTV .
   rm -rf $BINROOT/TBS-MatrixTV
fi

rm -rf $TARBALL_DIR

exit 0
